const questionsToAsk = [
  {
    id: 1,
    legend: "Quel type de climat préférez-vous ?",
    R1: "Chaud",
    R2: "Froid",
    R3: "Tempéré",
    Validate: "#R3",
  },
  {
    id: 2,
    legend: "Quelles sont vos envies d'activités pour ce voyage ?",
    R1: "Culinaire",
    R2: "Randonnées",
    R3: "Plage",
    R4: "Détente",
    R5: "Visites",
    R6: "Shopping",
    R7: "Fiesta",
    Validate: "#R7",
  },
  {
    id: 3,
    legend: "Vous êtes plutôt ?",
    R1: "Plage",
    R2: "Montagne",
    R3: "Ville",
    R4: "Campagne",
    Validate: "#R4",
  },
  {
    id: 4,
    legend: "Quel est votre budget ?",
    R1: "Petit",
    R2: "Moyen",
    R3: "Elevé",
    Validate: "#R3",
  },
  {
    id: 5,
    legend: "Quelle serait votre durée de voyage idéale ?",
    R1: "Week-end",
    R2: "Semaine",
    R3: "Nombre de jours",
    Validate: "#R3",
  },
  {
    id: 6,
    legend: "Pour ce voyage vous partez ?",
    R1: "Famille",
    R2: "Solo",
    R3: "A deux",
    R4: "Entre copains",
    Validate: "#R4",
  },
];

export default questionsToAsk;
